### ISSUE TITLE
Output is not a valid JSON

### ISSUE THREAD

**Issue by saekort** [mogmismo/pfs-sessiontracker-userscript#1]
Hey,

What the script outputs is not a valid JSON yet. A lot of `null` values are dotted through it.

Excerpt:

```
    null,
    {
        "date": "2016-04-09T07:00:00Z",
        "EventCode": "41481",
        "EventName": "Home game",
        "Session": "36",
        "GM": "Maglok",
        "Scenario": "#4–09: The Blakros Matrimony (RPG)",
        "Character": "",
        "Faction": "—",
        "Prestige": "GMn        n        —",
        "campaign": "RPG",
        "PFSNumber": "25642-",
        "ScenarioNumber": "409"
    },
    null,
    null,
    null,
    null,
    null,
    null,
    null
```

Those `null` values don't validate in json checkers. Since I am coding a import function that first checks if it is a valid input that won't do. :) For now I will just filter out all the `null` values and it should validate then, but maybe you can get rid of them through the flavour-monkey script here?

I would also appreciate if it could wrap it all in a array `[{object},{object}]`

**Comment by mogmismo** [comment]
Wow, I'm not getting that at all.  Perhaps something in your account that's not in mine.  Do you mind sending me the complete JSON from your account, and a screenshot of the page?  Maybe you have extra table rows.  I'm sure I can get them cleared out.  (Many other changes today)

**Comment by saekort** [comment]
Gonna look into it :)

**Comment by mogmismo** [comment]
Try it in Tampermonkey, looks like the null values are related somehow to Greasemonkey version only.  Also, I got session parsing working nicely:  Some of the scenarios that were not getting season / scenario number working correctly was because they were sometimes uses long hyphens _&#8212;_ or _0xE2_ instead of a regular hyphen, but their font/stylesheet made it not so obvious.

**Comment by mogmismo** [comment]
As of the latest version, a couple months ago, this issue if fixed.
