### ISSUE TITLE
Scenario/season numbers request

### ISSUE THREAD

**Issue by saekort** [mogmismo/pfs-sessiontracker-userscript#3]
At the moment you give me the `ScenarioNumber` field. This is a good start, you mentioned that you could define it however?

Is it possible to give me:
`"season": "8",
"scenario": "21"`

Like that? It would make determining what part of the number is the season easier for me. A bunch actually. :)

**Comment by mogmismo** [comment]
Yes, I can do that.  Before you go too much farther, I got a request for an enhancement: #2 which would mean more changes to the format.  That page mixes GM and Player data.  Could you accept a single dump file/stream with both GM and Player data, as long as there is a new field to differentiate?   It would also remove a step from the import process.

Also, implicit but not mentioned in that request from the VC that requested it: He wants to be able to pull data from users that are not him and import.  Does  your side only import for the logged in user, or will it import based on the data in the json?

**Comment by saekort** [comment]
I'll reply to that in the other topic then. :)

**Comment by mogmismo** [comment]
Done.  The raw value of the Scenario name is now stored in ScenarioName so we don't have "Scenario" and "scenario"
