### ISSUE TITLE
Login problems when using script

### ISSUE THREAD

**Issue by saekort** [mogmismo/pfs-sessiontracker-userscript#4]
A user created this issue on the tracker github: https://github.com/saekort/PFS-Scenariotracker/issues/41 

Seems more related to the greasemonkey script though.

**Comment by saekort** [comment]
Addendum: I was just reporting a session and it seems that greasemonkey kills 'normal' javascript behaviour when activated in the secure.paizo.com subdomain. Specifically I tried to select a date from the datepicker to report and the datepicker just lost its shit :p 

Disabled greasemonkey, worked again.

**Comment by mogmismo** [comment]
Yes, I moved from Tampermonkey to Greasemonkey, and noticed both the null fields in the JSON.  Looks like `delete object[key]` inside an each loop isn't working on greasemonkey either.  Going to try to get Greasemonkey working this week, but will be gone dark all weekend running EotT for a group....

**Comment by saekort** [comment]
Awesome! EotT! Have fun man.

**Comment by mogmismo** [comment]
I've poked at this, and with the latest version (0.3) can't replicate in greasemonkey.  Logging in works fine now.  #1 is still plaguing the Greasemonkey/Firefox installation, though.  That next.
